### ISSUE TITLE
Convert tree of life fluid crafts to per tick

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/.github#11]
### Modpack Version

Dev

### Describe your issue.

Reminder for myself. Forgot to normalize these with the rest

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
... How did this end up here instead of E6?

**Comment by NielsPilgaard** [comment]
Great question 😅
