### ISSUE TITLE
Superior shields 

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/.github#13]
### URL

https://www.curseforge.com/minecraft/mc-mods/superior-shields

### Why would you like the mod added?

Looks like a promising little mod with curio based energy shields.

**Comment by NielsPilgaard** [comment]
For E6 or? 😄

**Comment by MuteTiefling** [comment]
... Meant to post in e9. That's what I get for omg this on mobile I guess.

**Comment by MuteTiefling** [comment]
Moved to e9
