### ISSUE TITLE
Turn on laserdrillplanet

### ISSUE THREAD

**Issue by Cmonster820** [NillerMedDild/.github#16]
### Describe your suggestion

I would like to have the laserdrillplanet setting in the ar configs set to true

### Why would you like this added/changed?

People on servers might like this because they now can make a functioning Death Star, and some form of big weapon(although if you want a big weapon you could just add trinity)

**Comment by NielsPilgaard** [comment]
Not sure which modpack you're requesting this for, but the answer is no regardless, I'm worried it would be used as a griefing tool.
