### ISSUE TITLE
Enigmatica10 repository does not have "suggestion" label

### ISSUE THREAD

**Issue by purrloftruth** [NillerMedDild/.github#18]
### Modpack Version

n/a

### Describe your issue.

The issue templates suggestions.yml and mod-suggestions.yml attempt to add a label called "Suggestion" to new issues created, but that label doesn't exist in the Enigmatica10 repository, so it doesn't get added. Adding the label to the repository should ensure that it gets added on all new suggestion/mod suggestion issues. (I think?)

edit: In fact, notably, the labels in the E10 repo are completely different from the ones in the E9 repo.

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

purrloftruth

**Comment by NielsPilgaard** [comment]
Fixed thank you 😊
