### ISSUE TITLE
Mystical agriculture farmland doesn't work with Botany Pots

### ISSUE THREAD

**Issue by RuneOracle** [NillerMedDild/.github#7]
### Modpack Version

Enigmatica6-0.5.25

### Describe your issue.

I added mystical agriculture to a custom version of E6, I planned on using bees + seeds for ores, and I am unable to use any of the mystical agriculture farmland on botany pots, at first I thought it was a BP issue, but the developer informed me pack devs could disable features such as this, so im assuming that's what this is.

### Have you modified the modpack?

Yes

### User Modifications

Added Mystical Agriculture, using OptiFine, a few small mods that add items/QoL changes

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
We redid all recipes for Botany Pots iirc, so you'd have to add support through KubeJS if you want BP and MA to work together :)
